# Linux x86_64; install: conda env create -f environment.yml -p /icbb_triton/scratch/$USER/envs/plb

name: plb
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - -r requirements.lock
      - -e .
